package com.philipp.dv_projekt;

public enum ResponseType {
    AUDIO_GENERATION_REQUEST_SUCCESS,
    AUDIO_GENERATION_REQUEST_FAILURE,
    FAILURE,
    KNOWN_CUSTOMER,
    KNOWN_CUSTOMER_WITHOUT_APPOINTMENT,
    NEXT_APPOINTMENT,
    PERSON_DATA,
    PERSON_DATA_SUCCESS_FALSE,
    ROBOT_REACHED_GOAL,
    TERMIN_INFO,
    UNKNOWN_CUSTOMER,
    UNKNOWN_RESPONSE
}
